In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b=np.array([1,2,3,4],dtype=float)


In [4]:
d=np.array([[1,2,3],[4,5,6]])

In [5]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
e=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [7]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
e.ndim

2

In [9]:
e[0][1]

2

In [10]:
a=np.linspace(start=1,stop=10,num=8)

In [11]:
import numpy as np
a=np.linspace(start=1,stop=10,num=8)

In [12]:
print(a)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [13]:
c=np.arange(start=12,stop=20,dtype=float)

In [14]:
c

array([12., 13., 14., 15., 16., 17., 18., 19.])

In [15]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.random.rand(5,2)


array([[0.01455922, 0.16805064],
       [0.51068509, 0.86022395],
       [0.44502292, 0.44294459],
       [0.2947342 , 0.39945052],
       [0.06463302, 0.63135504]])

In [18]:
c=np.array([1,2,3,4,5,6])


In [19]:
c

array([1, 2, 3, 4, 5, 6])

In [20]:
c.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
d=c.reshape((1,6))


In [22]:
d

array([[1, 2, 3, 4, 5, 6]])

In [23]:
e=np.array([5,4,2,34,5,5])

In [24]:
c[1:3] #fetching row2 till row3

array([2, 3])

In [25]:
import numpy as np

In [26]:
e=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])