In [33]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
data=pd.read_csv("C:\\Users\\user\\Downloads\\Social_Network_Ads.csv")
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [19]:
x=data.iloc[:,2:4].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [17]:
y=data.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
s_c=StandardScaler()

In [24]:
x_train=s_c.fit_transform(x_train)

In [25]:
x_test=s_c.transform(x_test)

In [26]:
x_train

array([[-1.41421365e+00, -1.48276883e+00],
       [-1.13131199e+00,  3.92554188e-01],
       [-4.71208092e-01, -3.10691943e-01],
       [ 7.54699139e-01, -3.39993866e-01],
       [ 1.03760081e+00,  4.51158033e-01],
       [-1.03701143e+00,  5.68365721e-01],
       [ 1.79200526e+00, -1.30695730e+00],
       [-8.48410317e-01,  3.63252266e-01],
       [ 2.94689238e-04, -6.03711165e-01],
       [-2.82606980e-01,  2.23857528e+00],
       [ 3.77496914e-01,  2.29717913e+00],
       [ 1.13190136e+00, -7.79522698e-01],
       [-1.79141588e+00, -1.76727218e-02],
       [ 7.54699139e-01,  3.33950344e-01],
       [ 2.83196358e-01,  4.09311225e-02],
       [-1.69711532e+00,  3.33950344e-01],
       [ 9.45952455e-02,  1.85765030e+00],
       [ 3.77496914e-01,  2.46044578e-01],
       [-5.65508648e-01, -1.54137267e+00],
       [-8.48410317e-01,  2.26787721e+00],
       [-9.40058670e-02,  2.15066952e+00],
       [ 7.54699139e-01,  5.09761877e-01],
       [-6.59809204e-01, -1.07254192e+00],
       [-1.

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
classifier=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)

In [30]:
 #k=sqrt(no of training samples)/2

In [31]:
x_train.shape

(320, 2)

In [34]:
np.sqrt(320)/2

8.94427190999916

In [35]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [37]:
y_pred=classifier.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
cm=confusion_matrix(y_test,y_pred)

In [40]:
cm

array([[53,  2],
       [ 4, 21]], dtype=int64)

In [42]:
accuracy=(53+21)/(53+21+4+2)
accuracy

0.925